// Generated by CoffeeScript 1.6.3
(function() {
  var Attachment;

  Attachment = (function() {
    function Attachment() {}

    Attachment.data = null;

    return Attachment;

  })();

  exports.Attachment = Attachment;

}).call(this);
